test_cron.TestUpdateOsmStreets.test_http_error: avoid mocking
Which requires a bit of rework, now we no longer raise a HTTP error on
network problems, rather we return a bytes, error tuple.

Change-Id: I802119ec17f25179668b69ad658fcc6f38f51ec2