Clean up tcp_port from wsgi.ini.template
It's enough to document the default.

Also update to latest clap to fix the build, because otherwise it would
fail with:

	error: failed to select a version for the requirement `textwrap = "^0.15.1"`

(wtf?)

Change-Id: Ia5850c17020ed2fac74d19355cee2c64b4080e7a