Change urlopen() type hints to take string data and return string data
As that's what the implementation does. Otherwise we get:

  File "/home/osm-gimmisn/git/osm-gimmisn/cron.py", line 341, in our_main
    update_stats(ctx, overpass)
  File "/home/osm-gimmisn/git/osm-gimmisn/cron.py", line 308, in update_stats
    overpass_sleep(ctx)
  File "/home/osm-gimmisn/git/osm-gimmisn/cron.py", line 53, in overpass_sleep
    sleep = overpass_query.overpass_query_need_sleep(ctx)
  File "/home/osm-gimmisn/git/osm-gimmisn/overpass_query.py", line 29, in overpass_query_need_sleep
    buf, err = urlopen(ctx.get_ini().get_overpass_uri() + "/api/status", bytes())
TypeError: argument 'data': 'bytes' object cannot be converted to 'PyString'

Change-Id: I0f1098e7ef938f5d774e91ee70ab8fc0fca7aaba